version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres_sgv
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 128M
    environment:
      POSTGRES_USER: sgv
      POSTGRES_PASSWORD: sgv
      POSTGRES_DB: sgv
    volumes:
      - sgv-database-data:/var/lib/postgresql/data/

volumes:
  sgv-database-data: